language: "python"
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - "pip install --use-mirrors -r requirements.txt"
    - "pip install --use-mirrors -r tests/requirements.txt"
script:
    - "nosetests"
