language: "python"
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - "pip install --use-mirrors -r requirements.txt"
    - "pip install --use-mirrors coveralls"
script:
    - "nosetests --with-coverage --cover-package=aur"
after_success:
    - "coveralls"
